---
testLibraries:
- name: Component-01
  library: "../Component01/bin/Debug/net8.0/Component01.dll"
- name: Component-02
  library: "../Component02/bin/Debug/net8.0/Component02.dll"
testSuites:
  pullRequest:
  - testLibrary: Component-01
    testSets:
    - testLibrary: Component-01
      testSet: sanity
    - testLibrary: Component-02
      testSet: sanity
  - testLibrary: Component-02
    testSets:
    - testLibrary: Component-02
      testSet: regression
  nightly:
  - testLibrary: Component-01
    testSets:
    - testLibrary: Component-01
      testSet: regression
  - testLibrary: Component-02
    testSets:
    - testLibrary: Component-02
      testSet: regression
  weekend:
  - testLibrary: Component-01
    testSets:
    - testLibrary: Component-01
      testSet: performance
  - testLibrary: Component-02
    testSets:
    - testLibrary: Component-02
      testSet: performance
labConfig:
  name: DevCluster01
  networking:
    dns: some-lab-dns
    ip: 01.01.01.01